# Generated by Django 3.2.7 on 2021-09-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_faceitreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='eleagueReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=122)),
                ('tname', models.CharField(max_length=122)),
                ('femail', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
