# Generated by Django 3.2.7 on 2021-09-07 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_eleaguereg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleaguereg',
            old_name='femail',
            new_name='efemail',
        ),
        migrations.RenameField(
            model_name='eleaguereg',
            old_name='pname',
            new_name='epname',
        ),
        migrations.RenameField(
            model_name='eleaguereg',
            old_name='tname',
            new_name='etname',
        ),
    ]
